
#version: '3.8' # NOTE: もうversion指定が不要らしい
x-common:
  AWS_S3_ACCESS_KEY: &aws_s3_access_key minio
  AWS_S3_SECRET_KEY: &aws_s3_secret_key minio1234

services:
  api:
#    image: api:latest
#    pull_policy: never # bakeで事前実行を必須とする # これはなくてもいい
    build:
      context: .
      target: ${BUILD_TARGET:-dev}
      args:
        - RUNTIME_TAG=${RUNTIME_TAG}
#    read_only: true # TODO: これがあると動かない…？
    volumes:
      #      - .dockervenv:/src/.venv
      - .:/src
      - /tmp
#    environment:
#      ENV: local
#      S3_BUCKET: tmp.local
#      AWS_S3_ACCESS_KEY: *aws_s3_access_key
#      AWS_S3_SECRET_KEY: *aws_s3_secret_key
    ports:
      - 8000:8000
    networks:
      - development_network
  db:
    image: mysql:8.0
    platform: linux/x86_64  # M1 Macの場合必要
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # rootアカウントをパスワードなしで作成
      MYSQL_DATABASE: 'demo'  # 初期データベースとしてdemoを設定
      TZ: 'Asia/Tokyo'  # タイムゾーンを日本時間に設定
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password  # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
    ports:
      - 33306:3306  # ホストマシンのポート33306を、docker内のポート3306に接続する
    networks:
      - development_network
  storage:
    image: minio/minio
    entrypoint: sh
    command: -c "mkdir -p /data/data-exchange.local /data/tmp.local && /usr/bin/minio server --address :9000 --console-address :9001 /data"
    ports:
      - "9000:9000" # APIとして
      - "9001:9001" # consoleとして
    volumes:
      - minio_data:/data
#    tmpfs: /data # CI等で高速化する場合
    environment:
#      MINIO_ACCESS_KEY: *aws_s3_access_key
#      MINIO_SECRET_KEY: *aws_s3_secret_key
      MINIO_ROOT_USER: ${AWS_S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${AWS_S3_SECRET_KEY}
    env_file:
      - docker.env
    networks:
      - development_network
  kvs:
    image: 'redis:latest'
    volumes:
      - kvs_data:/data
    networks:
      - development_network
  mail:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
      - 1025:1025
    tmpfs:
      - /tmp # 元からメモリ展開されるので不要
    networks:
      - development_network
volumes:
  mysql_data:
  minio_data:
  kvs_data:
networks:
  development_network: