version: "3.9"

services:
  api: 
    build:
      context: .
      dockerfile: DockerfileDevelop
    image: api
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - ./app:/app
      - ./tests:/tests