version: "3.9"

services:
  api: 
    build:
      context: .
    image: api
    ports:
      - "18080:8080"
      - "180:80"
    volumes:
      - ./app:/app
  db:
    image: mysql:8.0.28
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: mysqld --character-set-server=utf8mb4 --sql-mode=0