name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: build
        run: export $(cat docker.env | xargs) && docker buildx bake
#      - name: build
#        run: docker compose build
#      - name: compose up -d
        # Mysqlの起動待ちで20秒
#        run: |
#          docker compose up -d
#          sleep 20
#      - name: test
#        run: docker-compose run --entrypoint "poetry run pytest --asyncio-mode=strict" api