name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: build or push
        run: |
          set -euxo pipefail
          export LOCK_HASH=python-$(sha1sum < uv.lock | cut -d' ' -f1)
          export RUNTIME_TAG=$LOCK_HASH
          if ! docker manifest inspect kirimaru/fastapi-practice_dev-runtime:$RUNTIME_TAG > /dev/null 2>&1; then
            # この環境変数が必要？
            # nocache必要？
            docker buildx create --name zstd-builder --use --platform linux/amd64
          
            # docker version
            # docker buildx version
          
            export $(grep -v '^#' docker.env | xargs) && docker buildx bake
          
            # docker images
          
            # docker.env の環境変数で上書きされているので再度上書き
            export RUNTIME_TAG=$LOCK_HASH
            docker tag api:latest kirimaru/fastapi-practice_dev-runtime:$RUNTIME_TAG
            docker push kirimaru/fastapi-practice_dev-runtime:$RUNTIME_TAG
          
            # TODO: なぜか　api:latest だけが pushされる
            echo "completed"
          fi

      #        run: export $(cat docker.env | xargs) && docker buildx bake
      #          docker pull kirimaru/fastapi-practice_dev-runtime:$RUNTIME_TAG && pull_status=$? || pull_status=$?
#      - name: build
#        run: docker compose build
#      - name: compose up -d
        # Mysqlの起動待ちで20秒
#        run: |
#          docker compose up -d
#          sleep 20
#      - name: test
#        run: docker-compose run --entrypoint "poetry run pytest --asyncio-mode=strict" api