name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: build or push
#        run: export $(cat docker.env | xargs) && docker buildx bake
        run: |
          export LOCK_HASH=python-$(sha1sum < uv.lock | cut -d' ' -f1)
          export RUNTIME_TAG=$LOCK_HASH

#          docker pull kirimaru/fastapi-practice_dev-runtime:$RUNTIME_TAG && pull_status=$? || pull_status=$?
          docker manifest inspect kirimaru/fastapi-practice_dev-runtime:$RUNTIME_TAG > /dev/null 2>&1
          if [ $? -eq 1 ]; then
            export $(cat docker.env | xargs) && docker buildx bake
            docker tag api:latest kirimaru/fastapi-practice_dev-runtime:$RUNTIME_TAG
            docker push kirimaru/fastapi-practice_dev-runtime:$RUNTIME_TAG
          fi
#      - name: build
#        run: docker compose build
#      - name: compose up -d
        # Mysqlの起動待ちで20秒
#        run: |
#          docker compose up -d
#          sleep 20
#      - name: test
#        run: docker-compose run --entrypoint "poetry run pytest --asyncio-mode=strict" api