name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: build or push
        run: |
          set -euxo pipefail
          export LOCK_HASH=python-$(sha1sum < uv.lock | cut -d' ' -f1)
          export RUNTIME_TAG=$LOCK_HASH
          if ! docker manifest inspect kirimaru/fastapi-practice_dev-runtime:$RUNTIME_TAG > /dev/null 2>&1; then
            docker buildx create --name builder --use --platform linux/amd64
          
            # bakeパターンだからうまくうごかない？
            # export $(grep -v '^#' docker.env | xargs) && docker buildx bake
            
            docker buildx build --builder builder --target dev_runtime -t kirimaru/fastapi-practice_dev-runtime:$RUNTIME_TAG --output type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true,push=true .
          
            ## 直接pushするやり方にしているので不要？
            # docker.env の環境変数で上書きされているので再度上書き
            # export RUNTIME_TAG=$LOCK_HASH
            # docker tag api:latest kirimaru/fastapi-practice_dev-runtime:$RUNTIME_TAG
            # docker push kirimaru/fastapi-practice_dev-runtime:$RUNTIME_TAG
          fi

      #        run: export $(cat docker.env | xargs) && docker buildx bake
      #          docker pull kirimaru/fastapi-practice_dev-runtime:$RUNTIME_TAG && pull_status=$? || pull_status=$?
#      - name: build
#        run: docker compose build
#      - name: compose up -d
        # Mysqlの起動待ちで20秒
#        run: |
#          docker compose up -d
#          sleep 20
#      - name: test
#        run: docker-compose run --entrypoint "poetry run pytest --asyncio-mode=strict" api