name: Python Test CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: build
        run: docker-compose build
      - name: test
        run: docker-compose run --entrypoint "poetry run pytest --asyncio-mode=strict" api