name: Test

#on: [push]
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

env:
  BUILD_TARGET: test

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
#      - name: Set up Python ${{ matrix.python-version }}
#        uses: actions/setup-python@v4
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Install Dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.lock
#          pip install -r requirements-dev.lock
#      - name: Lint with Ruff
#        run: |
#          ruff .
#        continue-on-error: true
#      - name: build
#        run: export $(cat docker.env | xargs) && docker buildx bake
      - name: pull
        run: |
          export LOCK_HASH=python-$(sha1sum < uv.lock | cut -d' ' -f1)
          export RUNTIME_TAG=$LOCK_HASH
          docker pull kirimaru/fastapi-practice_dev-runtime:$RUNTIME_TAG
      - name: compose up
        run: |
          echo "AAAAAAAAAA"
          echo $RUNTIME_TAG
          docker compose up -d
      - name: db migration
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 10
          command: docker compose exec api alembic upgrade head
#          command: alembic upgrade head
      - name: Test
#        run: pytest
#        run: docker compose exec api pytest
        run: docker compose exec -T api pytest --alluredir=/app/allure-results

      - name: Copy Allure results from container
        run: |
          docker cp $(docker compose ps -q api):/app/allure-results ./allure-results

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
